

services:
  labelstudio:
    image: heartexlabs/label-studio
    environment:
      - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true
      - LABEL_STUDIO_USERNAME=label@localhost
      - LABEL_STUDIO_PASSWORD=label.123
      - LABEL_STUDIO_USER_TOKEN=label-token
    ports:
      - "8080:8080"
    container_name: label-studio

  wam_label:
    image: xiaoyao9184/image-faulty:main
    container_name: image-faulty-label
    working_dir: /workspace/label
    # command: label-studio-ml start --root-dir /workspace label
    # fix https://github.com/HumanSignal/label-studio-ml-backend/issues/7
    command: python3 _wsgi.py -d -p 9090
    environment:
      - LABEL_STUDIO_API_KEY=label-token
      - MODEL_PATH=/root/.cache/huggingface/hub/models--xiaoyao9184--image-faulty/snapshots/3bc9ba7f84a5d8359a34ef3a7d5e9f6bec349d91
    ports:
      - "9090:9090"
    volumes:
      - ./../../cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
