name: faulty_api_env
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.10.14

  - nvidia::cuda==11.4.3
  - conda-forge::cudatoolkit==11.4.3
  - conda-forge::cudnn==8.9.7.29

  - pip:
    - -r ./flask/requirements.txt
    - -r ./ort-server/requirements-test.txt
    - -r ./gradio/requirements-gpu.txt
    - -r ./label/requirements_base.txt
    - -r ./label/requirements_core.txt
    - -r ./label/requirements_test.txt
