
# default python 3.10 in ubuntu 22.04
FROM nvidia/cuda:12.6.3-cudnn-runtime-ubuntu22.04

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libstdc++6 \
    ca-certificates \
    python3-setuptools \
    python3-wheel \
    python3-pip \
    git \
    unattended-upgrades \
    && unattended-upgrade \
    && rm -rf /var/lib/apt/lists/*

COPY ./FaultyImageAPI /app

COPY ./flask /workspace/flask
RUN pip3 install --no-cache-dir \
    -r /workspace/flask/requirements.txt

COPY ./gradio /workspace/gradio
RUN pip3 install --no-cache-dir \
    -r /workspace/gradio/requirements-gpu.txt

COPY ./label /workspace/label
RUN pip3 install --no-cache-dir \
    -r /workspace/label/requirements_base.txt \
    -r /workspace/label/requirements_core.txt

EXPOSE 5000
EXPOSE 7860
EXPOSE 9090

VOLUME /app/models
VOLUME /root/.cache
VOLUME /workspace/label/.pytest_cache
# VOLUME /workspace/label/cache.db

ENV GRADIO_SERVER_NAME="0.0.0.0"
ENV LABEL_STUDIO_URL=http://label-studio:8080

CMD ["flask", "--app", "api.py", "run"]
